import{a as S,S as q,i as h}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const x="44800078-24df89d06f24ed99fe7b62add",M="https://pixabay.com/api/";async function m(e,r=1){const s={key:x,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await S.get(M,{params:s})).data}let f;function p(e,r){const s=e.map(({likes:a,views:t,comments:o,downloads:n,webformatURL:v,largeImageURL:b})=>`
        <a href="${b}" class="card">
          <div class="card-img-top">
            <img src="${v}" alt="Image">
          </div>
          <div class="card-body">
            <p class="card-title">Likes: ${a}</p>
            <p class="card-text">Views: ${t}</p>
            <p class="card-text">Comments: ${o}</p>
            <p class="card-text">Downloads: ${n}</p>
          </div>
        </a>`).join("");r.insertAdjacentHTML("beforeend",s),f?f.refresh():f=new q(".gallery a")}function P(e){e.innerHTML=""}function y(e){e.classList.remove("hidden")}function g(e){e.classList.add("hidden")}function $(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}function B(e){iziToast.error({title:"Error",message:e})}let c="",l=1,w=0;const i=document.querySelector(".gallery"),E=document.querySelector(".search"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");E.addEventListener("submit",O);u.addEventListener("click",C);async function O(e){if(e.preventDefault(),c=e.currentTarget.elements.query.value.trim().toLowerCase(),!c){h.error({title:"Error",message:"Please enter a search term!"});return}l=1,P(i),L(u),y(d);try{const r=await m(c,l);if(w=r.totalHits,r.hits.length===0)throw new Error("No images found");p(r.hits,i),$(u)}catch(r){h.error({title:"Error",message:r.message||"Sorry, there are no images matching your search query. Please try again!"})}finally{g(d),E.reset()}}async function C(){l+=1,y(d);try{const e=await m(c,l);p(e.hits,i),i.children.length>=w&&(L(u),h.info({message:"Were sorry, but you've reached the end of search results."})),H()}catch(e){B(e.message)}finally{g(d)}}function H(){const{height:e}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
