import{a as b,S,i as f}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="44800078-24df89d06f24ed99fe7b62add",M="https://pixabay.com/api/";async function h(e,r=1){const s={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};return(await b.get(M,{params:s})).data}function m(e,r){const s=e.map(({likes:a,views:t,comments:o,downloads:n,webformatURL:E,largeImageURL:v})=>`
        <a href="${v}" class="card">
          <div class="card-img-top">
            <img src="${E}" alt="Image">
          </div>
          <div class="card-body">
            <p class="card-title">Likes: ${a}</p>
            <p class="card-text">Views: ${t}</p>
            <p class="card-text">Comments: ${o}</p>
            <p class="card-text">Downloads: ${n}</p>
          </div>
        </a>`).join("");r.insertAdjacentHTML("beforeend",s),new S(".gallery a").refresh()}function P(e){e.innerHTML=""}function p(e){e.classList.remove("hidden")}function y(e){e.classList.add("hidden")}function $(e){e.classList.remove("hidden")}function g(e){e.classList.add("hidden")}function x(e){iziToast.error({title:"Error",message:e})}let c="",l=1,L=0;const i=document.querySelector(".gallery"),w=document.querySelector(".search"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");w.addEventListener("submit",B);u.addEventListener("click",O);async function B(e){if(e.preventDefault(),c=e.currentTarget.elements.query.value.trim().toLowerCase(),!c){f.error({title:"Error",message:"Please enter a search term!"});return}l=1,P(i),g(u),p(d);try{const r=await h(c,l);if(L=r.totalHits,r.hits.length===0)throw new Error("No images found");m(r.hits,i),$(u)}catch(r){f.error({title:"Error",message:r.message||"Sorry, there are no images matching your search query. Please try again!"})}finally{y(d),w.reset()}}async function O(){l+=1,p(d);try{const e=await h(c,l);m(e.hits,i),i.children.length>=L&&(g(u),f.info({message:"Were sorry, but you've reached the end of search results."})),C()}catch(e){x(e.message)}finally{y(d)}}function C(){const{height:e}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
